tried writing update_tree function, added a MCT class, and a MCT attribute in Agent class (but currently thows TypeError: Agent.__init__() missing 1 required positional argument: 'mct'). mcts() now passing in a MCT tree rather than the root node